version: "3.9"
services:
    user_service:
        build: 
            context: .
            dockerfile: ./UserService/Dockerfile
        ports:
            - "8081:80"
        depends_on:
            - mssql
    post_service:
        build: 
            context: .
            dockerfile: ./PostService/Dockerfile
        ports:
            - "8082:80"
        depends_on:
            - mssql
    job_service:
        build: 
            context: .
            dockerfile: ./JobService/Dockerfile
        ports:
            - "8083:80"
        depends_on:
            - mssql
    message_service:
        build: 
            context: .
            dockerfile: ./MessageService/Dockerfile
        ports:
            - "8084:80"
        depends_on:
            - mssql
    mssql:
        container_name: mssql
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"