version: "3.9"
services:
    api_gateway:
        container_name: api_gateway
        build:
            context: .
            dockerfile: ./GatewayApi/Dockerfile
        ports:
            - "8080:80"
    user_service:
        container_name: user_service
        build: 
            context: .
            dockerfile: ./UserService/Dockerfile
        ports:
            - "8081:80"
        depends_on:
            - mssql
    post_service:
        container_name: post_service
        build: 
            context: .
            dockerfile: ./PostService/Dockerfile
        ports:
            - "8082:80"
        depends_on:
            - mssql
    job_service:
        container_name: job_service
        build: 
            context: .
            dockerfile: ./JobService/Dockerfile
        ports:
            - "8083:80"
        depends_on:
            - mssql
    message_service:
        container_name: message_service
        build: 
            context: .
            dockerfile: ./MessageService/Dockerfile
        ports:
            - "8084:80"
        depends_on:
            - mssql
    mssql:
        container_name: mssql
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"